org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#neogradle.subsystems.parchment.minecraftVersion=1.21
#neogradle.subsystems.parchment.mappingsVersion=2024.07.28

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.1)
neo_version=21.1.250
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=divinerpg_compat
mod_name=DivineRPG Compat
mod_license=All Rights Reserved
mod_version=1.0.5
mod_group_id=TeamDivineRPG.divinerpg
mod_authors=Nicusha, The_Lemon_Juiced
mod_description=Adds mod compatability for various mods to DivineRPG

## External Mod Properties
jei_version=19.53.0.426
rei_version=12.0.625
cloth_version=15.0.140
architectury_version=13.0.8
bookshelf_version=21.1.37
cucumber_version=8.0.16
mystical_agriculture_version=8.0.28
mystical_customization_version=6.0.2
iron_jetpacks_version=8.0.11
immersive_engineering_version=1.21.1-12.4.2-194
mekanism_version=1.21.1-10.7.19.85
ender_io_version=8.2.12-beta

divinerpg_id=7371103
jer_id=6506298
jade_id=6011258
resource_pandas_id=5505741
advanced_mining_dimension_id=4688892
productivebees_id=8022994
enderio_id=6081623
common_capabilities_id=8469575
cyclops_core_id=8831960
integrated_dynamics_id=8830886
industrial_foregoing_id=8370717
titanium_id=8760562
pneumaticcraft_id=8519226
immersive_portals_id=6667779
cloth_id=5729127