org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#neogradle.subsystems.parchment.minecraftVersion=1.21
#neogradle.subsystems.parchment.mappingsVersion=2024.07.28

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.1)
neo_version=21.1.139
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=divinerpg_compat
mod_name=DivineRPG Compat
mod_license=All Rights Reserved
mod_version=1.0.4
mod_group_id=TeamDivineRPG.divinerpg
mod_authors=NicosaurusRex99, The_Lemon_Juiced
mod_description=Adds mod compatability for various mods to DivineRPG

## External Mod Properties
jei_version=19.21.0.247
rei_version=12.0.625
cloth_version=15.0.140
architectury_version=13.0.8
bookshelf_version=21.1.37
cucumber_version=8.0.8
mystical_agriculture_version=8.0.11
mystical_customization_version=6.0.0
iron_jetpacks_version=8.0.6
immersive_engineering_version=1.21.1-12.1.0-185
mekanism_version=1.21.1-10.7.13.78
ender_io_version=7.1.7-alpha

divinerpg_id=6178351
jer_id=6190140
jade_id=6011258
resource_pandas_id=5505741
advanced_mining_dimension_id=4688892
productivebees_id=6335286
enderio_id=6081623
common_capabilities_id=6059616
cyclops_core_id=6059640
integrated_dynamics_id=6083649
industrial_foregoing_id=5802805
titanium_id=5897690
pneumaticcraft_id=6288626