modLoader="javafml"
loaderVersion = "[${loader_version_range},)"
license="All rights reserved"
issueTrackerURL="https://github.com/DivineRPG/DivineRPG-Compat/issues"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
updateJSONURL = "https://raw.githubusercontent.com/DivineRPG/DivineRPG-Assets/main/divinerpg_compat.json" #optional
displayURL = "https://www.curseforge.com/minecraft/mc-mods/divinerpg-compatability" #optional
logoFile = "logo.png" #optional
credits = "NicosaurusRex99, The_Lemon_Juiced" #optional
description = '''Adds compatability for various mods to DivineRPG'''

[[dependencies.divinerpg]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"
# Non-Mandatory Dependencies
# Integrated Dynamics Optional Dependencies
[[dependencies.divinerpg_compat]]
    modId="commoncapabilities"
    mandatory=false
    versionRange = "[2.8.3,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.divinerpg_compat]]
    modId="cyclopscore"
    mandatory=false
    versionRange="[1.17.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.divinerpg_compat]]
    modId="integrateddynamics"
    mandatory=false
    versionRange="[1.14.8,)"
    ordering="NONE"
    side="BOTH"