modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/DivineRPG/DivineRPG-Compat/issues"
[[mods]]
modId="divinerpg_compat"
version="${file.jarVersion}"
displayName="DivineRPG Compatability"
updateJSONURL = "https://raw.githubusercontent.com/DivineRPG/DivineRPG-Assets/main/divinerpg_compat.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/divinerpg-compatability"
authors="NicosaurusRex99, The_Lemon_Juiced"
description='''
Compat
'''
[[dependencies.divinerpg_compat]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.divinerpg_compat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.divinerpg_compat]]
    modId="divinerpg"
    mandatory=true
    versionRange="[1.9.7, )"
    ordering="NONE"
    side="BOTH"

# Non-Mandatory Dependencies
# Integrated Dynamics Optional Dependencies
[[dependencies.divinerpg_compat]]
    modId="commoncapabilities"
    mandatory=false
    versionRange = "[2.8.3,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.divinerpg_compat]]
    modId="cyclopscore"
    mandatory=false
    versionRange="[1.17.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.divinerpg_compat]]
    modId="integrateddynamics"
    mandatory=false
    versionRange="[1.14.8,)"
    ordering="NONE"
    side="BOTH"