modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/DivineRPG/DivineRPG-Compat/issues"
[[mods]]
modId="divinerpg_compat"
version="${file.jarVersion}"
displayName="DivineRPG Compatability"
updateJSONURL = "https://raw.githubusercontent.com/DivineRPG/DivineRPG-Assets/main/divinerpg_compat.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/divinerpg-compatability"
authors="NicosaurusRex99, The_Lemon_Juiced"
description='''
Compat
'''
[[dependencies.divinerpg_compat]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.divinerpg_compat]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2, )"
ordering="NONE"
side="BOTH"
[[dependencies.divinerpg_compat]]
modId="divinerpg"
mandatory=true
versionRange="[1.9.6, )"
ordering="NONE"
side="BOTH"
